### PR TITLE
Feature/migrate 2 swift

### PR DESCRIPTION
**Pull request by arrrnas**
Swift framework for vinted-ab @vinted/ios

### CODE REVIEW

**Comment by arrrnas** [comment]
tests pass: https://github.com/arrrnas/vinted-ab-ios/pull/2, would be nice to enable travis-ci on this repository also.

**Comment by arrrnas** [comment]
For `CommonCrypto` I've followed http://stackoverflow.com/a/29189873 which seems like it should work the best since the same approach is used in https://github.com/stephencelis/SQLite.swift and https://github.com/soffes/CommonCrypto

**Comment by arrrnas** [comment]
@vinted/ios bump

**Comment by ajanauskas** [comment]
If it works - merge ¯\_(ツ)_/¯

PR too big to review

**Comment by arrrnas** [comment]
>Only those with write access to this repository can merge pull requests.

:/

**Pull request merged**
